apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t35k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t35k
    app.kubernetes.io/part-of: devfile-sample-1
  name: devfile-sample-t35k
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-t35k
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-t35k
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rsoaresd-tenant/devfile-sample-1/devfile-sample-t35k@sha256:81b089dc6a14017c9f70ab94af2e4b39db510b5156ecdf63eeaa036f925ea2ad
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
